platform :ios, '6.0'

pod 'AFNetworking', '1.1.0'
pod 'Reachability', '3.1.0'
pod 'MBProgressHUD', '0.6pre'
pod 'Underscore.m', '0.2.0'
pod 'GoogleAnalytics-iOS-SDK', '2.0beta4'
#pod 'Parse', '1.1.30'
#pod 'KYCircleMenu', '~> 1.0.1'
#pod 'iCarousel', '~> 1.7.4'
